#include "../syscalls.h";
#include "numberprinter.asm";
#define angle 42;
#define ar 0.733038;
#define str1 "Starting Angle (degrees): ";
#define str2 "Starting Angle (radians): ";
#define str3 "Cos: ";
#define str4 "Sin: ";
#define str5 "Tan: ";
#define str6 "Hypot: ";
#define str7 "Arcsin: ";
#define str8 "Arccos: ";
#define str9 "Arctan: ";
#define tri "Using triangle with length 5, and with 7";
push &str1;
push angle;
call print;
push &str2;
div math.pi,180;
mulf %F,angle;
push %F;
call print;
push &str3;
sys math.cos ar,%F;
push %F;
call print;
push &str4;
sys math.sin ar,%F;
push %F;
call print;
push &str5;
sys math.tan ar,%F;
push %F;
call print;
sys sys.printString &tri;
push &str6;
sys math.hypot 5,7,%F;
push %F;
call print;
push &str7;
sys math.asin ar,%F;
push %F;
call print;
push &str8;
sys math.acos ar,%F;
push %F;
call print;
push &str9;
sys math.atan ar,%F;
push %F;
call print;